// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import ()

type Todo struct {
	ID          int64  `json:"id"`
	Username    string `json:"username"`
	Category    string `json:"category"`
	Title       string `json:"title"`
	Description string `json:"description"`
	IsDone      int64  `json:"is_done,bool"`
}

type TodoSearch struct {
	Category string `json:"category"`
	Title    string `json:"title"`
}

type User struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
